export const ADD_ALL_POINTS = 'ADD_ALL_POINTS';
export const ADD_SINGLE_POINTS = 'ADD_SINGLE_POINTS';
export const ADD_MULTIPLE_POINTS = 'ADD_MULTIPLE_POINTS';

export const ADD_SINGLE_POINTS_SUCCESS = 'ADD_SINGLE_POINTS_SUCCESS';
export const ADD_SINGLE_POINTS_ERROR = 'ADD_SINGLE_POINTS_ERROR';